/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.inserir;

import controller.IngredienteController;
import controller.ProdutoController;
import controller.SuprimentoController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.negocio.Ingrediente;
import modelo.negocio.Produto;
import modelo.negocio.Suprimento;

public class InserirProduto extends javax.swing.JFrame {

    //Suprimento para produção
    private JTable tabelaIngrediente;
    private DefaultTableModel modeloIngrediente = new DefaultTableModel();

    //Produto
    private DefaultTableModel modelo;
    private int linhaSelecionada;

    //INSERIR
    public InserirProduto(DefaultTableModel modelo) {
        initComponents();
        setLocationRelativeTo(null);
        this.modelo = modelo;
        setResizable(false);
        criaJTable();
        painelIngrediente.setViewportView(tabelaIngrediente);
    }

    //EDITAR LINHA SELECIONADA 
    public InserirProduto(DefaultTableModel modelo, int linhaSelecionada, int idProduto) {
        this.modelo = modelo;

        preencherCampos(linhaSelecionada, idProduto);

    }

    //VISUALIZAR LINHA SELECIONADA
    public InserirProduto(int linhaSelecionada, int idProduto) {
        preencherCampos(linhaSelecionada, idProduto);
        bloquearCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        cadastroProduto = new javax.swing.JPanel();
        nome = new javax.swing.JLabel();
        descricao = new javax.swing.JLabel();
        scrollDescricao = new javax.swing.JScrollPane();
        txDescricao = new javax.swing.JTextArea();
        txNome = new javax.swing.JTextField();
        btAdicionar = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        txId = new javax.swing.JTextField();
        painelIngrediente = new javax.swing.JScrollPane();
        jSeparator1 = new javax.swing.JSeparator();
        btSalvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        painelFundo.setBackground(new java.awt.Color(217, 176, 60));
        painelFundo.setPreferredSize(new java.awt.Dimension(800, 600));
        painelFundo.setRequestFocusEnabled(false);

        cadastroProduto.setBackground(new java.awt.Color(255, 255, 153));
        cadastroProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        cadastroProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        nome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nome.setText("NOME");

        descricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        descricao.setText("DESCRIÇÃO");

        txDescricao.setColumns(20);
        txDescricao.setRows(5);
        scrollDescricao.setViewportView(txDescricao);

        btAdicionar.setText("ADICIONAR");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btDeletar.setText("REMOVER");
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        id.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        id.setText("ID");

        txId.setEditable(false);

        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGREDIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        javax.swing.GroupLayout cadastroProdutoLayout = new javax.swing.GroupLayout(cadastroProduto);
        cadastroProduto.setLayout(cadastroProdutoLayout);
        cadastroProdutoLayout.setHorizontalGroup(
            cadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroProdutoLayout.createSequentialGroup()
                        .addGroup(cadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroProdutoLayout.createSequentialGroup()
                                .addComponent(descricao)
                                .addGap(18, 18, 18)
                                .addComponent(scrollDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cadastroProdutoLayout.createSequentialGroup()
                                .addComponent(nome)
                                .addGap(31, 31, 31)
                                .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(463, Short.MAX_VALUE))
                    .addGroup(cadastroProdutoLayout.createSequentialGroup()
                        .addGroup(cadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroProdutoLayout.createSequentialGroup()
                                .addComponent(id)
                                .addGap(18, 18, 18)
                                .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cadastroProdutoLayout.createSequentialGroup()
                                .addGroup(cadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(painelIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 287, Short.MAX_VALUE))))
            .addComponent(jSeparator1)
        );
        cadastroProdutoLayout.setVerticalGroup(
            cadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroProdutoLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(cadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(cadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descricao)
                    .addComponent(scrollDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cadastroProdutoLayout.createSequentialGroup()
                        .addComponent(btAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDeletar)))
                .addGap(34, 34, 34))
        );

        btSalvar.setText("SALVAR");
        btSalvar.setBorderPainted(false);
        btSalvar.setContentAreaFilled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jButton1.setText("LIMPAR");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);

        javax.swing.GroupLayout painelFundoLayout = new javax.swing.GroupLayout(painelFundo);
        painelFundo.setLayout(painelFundoLayout);
        painelFundoLayout.setHorizontalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cadastroProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(78, 78, 78))
        );
        painelFundoLayout.setVerticalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFundoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(jButton1))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        Produto p = new Produto();
        p.setNome(txNome.getText());
        p.setDescricao(txDescricao.getText());

        ProdutoController pc = new ProdutoController();

        if (!(txId.getText().equals("") | (txId.getText().equals(null)))) {
            p.setCodigo(Integer.parseInt(txId.getText()));
            pc.salvar(p);

            modelo.removeRow(linhaSelecionada);
            modelo.addRow(new Object[]{p.getCodigo(), p.getNome(), p.getDescricao()});
            dispose();

        } else {
            pc.salvar(p);
            dispose();
        }


    }//GEN-LAST:event_btSalvarActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed

        InserirIngrediente novo = new InserirIngrediente(modeloIngrediente);
        novo.setVisible(true);

    }//GEN-LAST:event_btAdicionarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        modeloIngrediente.setNumRows(0);
        preencherJTable();

    }//GEN-LAST:event_formWindowGainedFocus

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarActionPerformed
        int linhaSelecionadaIngrediente = -1;
        linhaSelecionadaIngrediente = tabelaIngrediente.getSelectedRow();

        if (linhaSelecionadaIngrediente >= 0) {
            int idIngrediente = (int) tabelaIngrediente.getValueAt(linhaSelecionadaIngrediente, 0);

            IngredienteController ic = new IngredienteController();
            if (ic.excluir(idIngrediente));
            {
                modeloIngrediente.removeRow(linhaSelecionadaIngrediente);
            }
        } else {
            JOptionPane.showMessageDialog(null, "SELECIONE UMA LINHA");

        }    }//GEN-LAST:event_btDeletarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JPanel cadastroProduto;
    private javax.swing.JLabel descricao;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nome;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JScrollPane painelIngrediente;
    private javax.swing.JScrollPane scrollDescricao;
    private javax.swing.JTextArea txDescricao;
    private javax.swing.JTextField txId;
    private javax.swing.JTextField txNome;
    // End of variables declaration//GEN-END:variables

    private void preencherCampos(int linhaSelecionada1, int idProduto) {
        initComponents();
        this.linhaSelecionada = linhaSelecionada1;
        setLocationRelativeTo(null);
        ProdutoController pc = new ProdutoController();
        Produto p = pc.listarProdutoPorId(idProduto);

        txId.setText(String.valueOf(p.getCodigo()));
        txNome.setText(p.getNome());
        txDescricao.setText(p.getDescricao());

    }

    private void bloquearCampos() {

        txDescricao.setEditable(false);
        txNome.setEditable(false);

    }

//    Carregar comboBox com suprimentos que são para produção
//    private void carregarCombo() {
//
//        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbIngrediente.getModel();
//        comboModel.removeAllElements();
//        List<Suprimento> s = new ArrayList<>();
//
//        SuprimentoController sc = new SuprimentoController();
//        s = sc.listarSuprimento();
//
//        for (int linha = 0; linha < s.size(); linha++) {
//            Suprimento sb = s.get(linha);
//            if (sb.getProducao() == 'S') {
//
//                comboModel.addElement(sb);
//
//            }
//        }
//    }
    private void criaJTable() {

        tabelaIngrediente = new JTable(modeloIngrediente) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modeloIngrediente.addColumn("PRODUTO");
        modeloIngrediente.addColumn("QUANTIDADE");
        modeloIngrediente.addColumn("UNIDADE MEDIDA");

        preencherJTable();
    }

    private void preencherJTable() {

        IngredienteController sc = new IngredienteController();
        for (Ingrediente s : sc.listarIngrediente()) {
            modeloIngrediente.addRow(new Object[]{s.getNome(), s.getQntidade(), s.getMedida()});

        }

    }
}
