package view.inserir;

import controller.FornecedorController;
import javax.swing.table.DefaultTableModel;
import modelo.negocio.Endereco;
import modelo.negocio.Fornecedor;

public class InserirFornecedor extends javax.swing.JFrame {
    
    private DefaultTableModel modelo;
    private int linhaSelecionada;

    //INSERIR NOVO
    public InserirFornecedor(DefaultTableModel modelo) {
        initComponents();
        setLocationRelativeTo(null);
        this.modelo = modelo;
    }

    //EDITAR LINHA SELECIONADA
    public InserirFornecedor(DefaultTableModel modelo, int linhaSelecionada, int idFornecedor) {
        this.modelo = modelo;
        PreencherCampos(linhaSelecionada, idFornecedor);
    }

    //VISUALIZAR LINHA SELECIONADA
    public InserirFornecedor(int linhaSelecionada, int idFornecedor) {
        PreencherCampos(linhaSelecionada, idFornecedor);
        bloquearCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        cadastroFornecedor = new javax.swing.JTabbedPane();
        dadosFornecedor = new javax.swing.JPanel();
        nome = new javax.swing.JLabel();
        txNome = new javax.swing.JTextField();
        telefone = new javax.swing.JLabel();
        txTelefone = new javax.swing.JFormattedTextField();
        fax = new javax.swing.JLabel();
        txFax = new javax.swing.JFormattedTextField();
        email = new javax.swing.JLabel();
        txEmail = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        txId = new javax.swing.JTextField();
        campoObrigatorio = new javax.swing.JLabel();
        cnpj = new javax.swing.JLabel();
        txCnpj = new javax.swing.JFormattedTextField();
        endereco = new javax.swing.JPanel();
        rua = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        txNumero = new javax.swing.JTextField();
        txRua = new javax.swing.JTextField();
        complemento = new javax.swing.JLabel();
        txComplemento = new javax.swing.JTextField();
        estado = new javax.swing.JLabel();
        txEstado = new javax.swing.JTextField();
        cidade = new javax.swing.JLabel();
        txCidade = new javax.swing.JTextField();
        idEndereco = new javax.swing.JLabel();
        txIdEndereco = new javax.swing.JTextField();
        cep = new javax.swing.JLabel();
        txCep = new javax.swing.JFormattedTextField();
        bairro = new javax.swing.JLabel();
        txBairro = new javax.swing.JTextField();
        tipoProduto = new javax.swing.JPanel();
        nomeProduto = new javax.swing.JLabel();
        txNomeProduto = new javax.swing.JTextField();
        marcaProduto = new javax.swing.JLabel();
        txMarcaProduto = new javax.swing.JTextField();
        descricao = new javax.swing.JLabel();
        scrollDescricao = new javax.swing.JScrollPane();
        txDescricao = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelFundo.setBackground(new java.awt.Color(217, 176, 60));
        painelFundo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORNECEDOR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        painelFundo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        painelFundo.setMaximumSize(new java.awt.Dimension(800, 600));
        painelFundo.setMinimumSize(new java.awt.Dimension(800, 600));
        painelFundo.setRequestFocusEnabled(false);

        dadosFornecedor.setBackground(new java.awt.Color(255, 255, 153));

        nome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nome.setText("NOME *");

        telefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        telefone.setText("TELEFONE *");

        try {
            txTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTelefoneActionPerformed(evt);
            }
        });

        fax.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fax.setText("FAX");

        try {
            txFax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        email.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        email.setText("EMAIL*");

        id.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        id.setText("ID:");

        txId.setEditable(false);

        campoObrigatorio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campoObrigatorio.setText("* CAMPO OBRIGATÓRIO");

        cnpj.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cnpj.setText("CNPJ");

        javax.swing.GroupLayout dadosFornecedorLayout = new javax.swing.GroupLayout(dadosFornecedor);
        dadosFornecedor.setLayout(dadosFornecedorLayout);
        dadosFornecedorLayout.setHorizontalGroup(
            dadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosFornecedorLayout.createSequentialGroup()
                .addGroup(dadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosFornecedorLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(id)
                        .addGap(18, 18, 18)
                        .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosFornecedorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(dadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome)
                            .addGroup(dadosFornecedorLayout.createSequentialGroup()
                                .addGroup(dadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fax)
                                    .addComponent(email)
                                    .addComponent(cnpj)
                                    .addComponent(telefone))
                                .addGap(50, 50, 50)
                                .addGroup(dadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txFax, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(dadosFornecedorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(campoObrigatorio)))
                .addGap(0, 127, Short.MAX_VALUE))
        );
        dadosFornecedorLayout.setVerticalGroup(
            dadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosFornecedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome))
                .addGap(20, 20, 20)
                .addGroup(dadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefone)
                    .addComponent(txTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosFornecedorLayout.createSequentialGroup()
                        .addGroup(dadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fax))
                        .addGap(20, 20, 20)
                        .addGroup(dadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email)
                            .addComponent(txEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(cnpj)
                        .addGap(15, 15, 15))
                    .addComponent(txCnpj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(campoObrigatorio)
                .addGap(221, 221, 221))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id))
                .addGap(167, 167, 167))
        );

        cadastroFornecedor.addTab("DADOS DO FORNECEDOR", dadosFornecedor);

        endereco.setBackground(new java.awt.Color(255, 255, 153));

        rua.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rua.setText("RUA  *");

        numero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numero.setText("NÚMERO *");

        complemento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        complemento.setText("COMPLEMENTO");

        estado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        estado.setText("ESTADO *");

        txEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txEstadoActionPerformed(evt);
            }
        });

        cidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cidade.setText("CIDADE  *");

        idEndereco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        idEndereco.setText("ID");

        txIdEndereco.setEditable(false);

        cep.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cep.setText("CEP");

        bairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bairro.setText("BAIRRO");

        txBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBairroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enderecoLayout = new javax.swing.GroupLayout(endereco);
        endereco.setLayout(enderecoLayout);
        enderecoLayout.setHorizontalGroup(
            enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numero)
                    .addComponent(rua)
                    .addComponent(estado)
                    .addComponent(cep)
                    .addComponent(cidade)
                    .addComponent(bairro)
                    .addGroup(enderecoLayout.createSequentialGroup()
                        .addComponent(idEndereco)
                        .addGap(18, 18, 18)
                        .addComponent(txIdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txRua)
                        .addComponent(txCidade)
                        .addComponent(txBairro)
                        .addGroup(enderecoLayout.createSequentialGroup()
                            .addComponent(txNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(complemento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txCep, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        enderecoLayout.setVerticalGroup(
            enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidade)
                    .addComponent(txCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairro)
                    .addComponent(txBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rua))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero)
                    .addComponent(txNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complemento)
                    .addComponent(txComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estado)
                    .addComponent(txEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cep))
                .addGap(18, 18, 18)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idEndereco)
                    .addComponent(txIdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        cadastroFornecedor.addTab("ENDEREÇO", endereco);

        tipoProduto.setBackground(new java.awt.Color(255, 255, 153));

        nomeProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nomeProduto.setText("NOME DO PRODUTO *");

        marcaProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        marcaProduto.setText("MARCA DO PRODUTO *");

        descricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        descricao.setText("DESCRIÇÃO");

        txDescricao.setColumns(20);
        txDescricao.setRows(5);
        scrollDescricao.setViewportView(txDescricao);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("ID");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tipoProdutoLayout = new javax.swing.GroupLayout(tipoProduto);
        tipoProduto.setLayout(tipoProdutoLayout);
        tipoProdutoLayout.setHorizontalGroup(
            tipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipoProdutoLayout.createSequentialGroup()
                .addGroup(tipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tipoProdutoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(tipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txMarcaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tipoProdutoLayout.createSequentialGroup()
                                .addGroup(tipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descricao)
                                    .addComponent(nomeProduto)
                                    .addComponent(marcaProduto))
                                .addGroup(tipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tipoProdutoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(tipoProdutoLayout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(scrollDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(tipoProdutoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        tipoProdutoLayout.setVerticalGroup(
            tipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipoProdutoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeProduto)
                    .addComponent(txNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(tipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txMarcaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marcaProduto))
                .addGap(20, 20, 20)
                .addGroup(tipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricao))
                .addGap(20, 20, 20)
                .addGroup(tipoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        cadastroFornecedor.addTab("TIPO DE PRODUTO", tipoProduto);

        btSalvar.setText("SALVAR");
        btSalvar.setBorderPainted(false);
        btSalvar.setContentAreaFilled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btLimpar.setText("LIMPAR");
        btLimpar.setBorderPainted(false);
        btLimpar.setContentAreaFilled(false);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelFundoLayout = new javax.swing.GroupLayout(painelFundo);
        painelFundo.setLayout(painelFundoLayout);
        painelFundoLayout.setHorizontalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cadastroFornecedor)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar)
                .addGap(18, 18, 18)
                .addComponent(btLimpar)
                .addGap(145, 145, 145))
        );
        painelFundoLayout.setVerticalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFundoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cadastroFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txDescricao.setText(null);
        txEmail.setText(null);
        txFax.setText(null);
        txMarcaProduto.setText(null);
        txNome.setText(null);
        txNomeProduto.setText(null);
        txTelefone.setText(null);
        
        txCidade.setText(null);
        txComplemento.setText(null);
        txEstado.setText(null);
        txNumero.setText(null);
        txRua.setText(null);
        txCep.setText(null);
        txBairro.setText(null);

    }//GEN-LAST:event_btLimparActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Fornecedor f = new Fornecedor();
        
        f.setCnpj(txCnpj.getText());
        f.setDescricao(txDescricao.getText());
        f.setEmail(txEmail.getText());
        f.setFax(txFax.getText());
        f.setMarcaProduto(txMarcaProduto.getText());
        f.setNomeFantasia(txNome.getText());
        f.setNomeProduto(txNomeProduto.getText());
        f.setTelefone(txTelefone.getText());
    
        
        Endereco e = new Endereco();
        e.setCidade(txCidade.getText());
        e.setComplemento(txComplemento.getText());
        e.setEstado(txEstado.getText());
        e.setNumero(Integer.parseInt(txNumero.getText()));
        e.setRua(txRua.getText());
        e.setCep(txCep.getText());
        e.setBairro(txBairro.getText());
        
        if (!(txIdEndereco.getText().equals("") | (txIdEndereco.getText().equals(null)))) {
            e.setCodigo(Integer.parseInt(txIdEndereco.getText()));
        }
        f.setEndereco(e);
        
        FornecedorController fc = new FornecedorController();
        if (!(txId.getText().equals("") | (txId.getText().equals(null)))) {
            f.setCodigo(Integer.parseInt(txId.getText()));
            fc.salvar(f);
            
            modelo.removeRow(linhaSelecionada);
            modelo.addRow(new Object[]{f.getCodigo(), f.getCnpj(), f.getDescricao(), f.getEmail(), f.getFax(), f.getMarcaProduto(), f.getNomeFantasia(), f.getNomeProduto(), f.getTelefone()});
            dispose();
        } else {
            fc.salvar(f);
            dispose();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void txEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txEstadoActionPerformed

    private void txBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txBairroActionPerformed

    private void txTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTelefoneActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bairro;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTabbedPane cadastroFornecedor;
    private javax.swing.JLabel campoObrigatorio;
    private javax.swing.JLabel cep;
    private javax.swing.JLabel cidade;
    private javax.swing.JLabel cnpj;
    private javax.swing.JLabel complemento;
    private javax.swing.JPanel dadosFornecedor;
    private javax.swing.JLabel descricao;
    private javax.swing.JLabel email;
    private javax.swing.JPanel endereco;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel fax;
    private javax.swing.JLabel id;
    private javax.swing.JLabel idEndereco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel marcaProduto;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel nomeProduto;
    private javax.swing.JLabel numero;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JLabel rua;
    private javax.swing.JScrollPane scrollDescricao;
    private javax.swing.JLabel telefone;
    private javax.swing.JPanel tipoProduto;
    private javax.swing.JTextField txBairro;
    private javax.swing.JFormattedTextField txCep;
    private javax.swing.JTextField txCidade;
    private javax.swing.JFormattedTextField txCnpj;
    private javax.swing.JTextField txComplemento;
    private javax.swing.JTextArea txDescricao;
    private javax.swing.JTextField txEmail;
    private javax.swing.JTextField txEstado;
    private javax.swing.JFormattedTextField txFax;
    private javax.swing.JTextField txId;
    private javax.swing.JTextField txIdEndereco;
    private javax.swing.JTextField txMarcaProduto;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txNomeProduto;
    private javax.swing.JTextField txNumero;
    private javax.swing.JTextField txRua;
    private javax.swing.JFormattedTextField txTelefone;
    // End of variables declaration//GEN-END:variables

    private void PreencherCampos(int linhaSelecionada1, int idFornecedor) {
        initComponents();
        this.linhaSelecionada = linhaSelecionada1;
        setLocationRelativeTo(null);
        FornecedorController fc = new FornecedorController();
        Fornecedor f = fc.listarFornecedorPorId(idFornecedor);
        //FORNECEDOR
        txId.setText(String.valueOf(f.getCodigo()));
        txDescricao.setText(f.getDescricao());
        txEmail.setText(f.getEmail());
        txFax.setText(f.getFax());
        txMarcaProduto.setText(f.getMarcaProduto());
        txNome.setText(f.getNomeFantasia());
        txNomeProduto.setText(f.getNomeProduto());
        txTelefone.setText(f.getTelefone());
        //ENDEREÇO
        txCidade.setText(String.valueOf(f.getEndereco().getCidade()));
        txComplemento.setText(String.valueOf(f.getEndereco().getComplemento()));
        txEstado.setText(String.valueOf(f.getEndereco().getEstado()));
        txNumero.setText(String.valueOf(f.getEndereco().getNumero()));
        txRua.setText(String.valueOf(f.getEndereco().getRua()));
        txIdEndereco.setText(String.valueOf(f.getEndereco().getCodigo()));
        txCep.setText(f.getEndereco().getCep());
        txBairro.setText(f.getEndereco().getBairro());
    }
    
    private void bloquearCampos() {
        
        txCep.setEditable(false);
        txCidade.setEditable(false);
        txCnpj.setEditable(false);
        txComplemento.setEditable(false);
        txDescricao.setEditable(false);
        txEmail.setEditable(false);
        txEstado.setEditable(false);
        txFax.setEditable(false);
        txMarcaProduto.setEditable(false);
        txNome.setEditable(false);
        txNomeProduto.setEditable(false);
        txNumero.setEditable(false);
        txRua.setEditable(false);
        txTelefone.setEditable(false);
        btLimpar.setEnabled(false);
        btSalvar.setEnabled(false);
        txBairro.setEditable(false);
        
    }
    
}
