package view.inserir;

import controller.FuncionarioController;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.negocio.Endereco;
import modelo.negocio.Funcionario;

public class InserirFuncionario extends javax.swing.JFrame {
    
    private DefaultTableModel modelo;
    private int linhaSelecionada;

    //Inserir novo
    public InserirFuncionario(DefaultTableModel modelo) {
        initComponents();
        setLocationRelativeTo(null);
        this.modelo = modelo;
    }

    //Visualizar
    public InserirFuncionario(int linhaSelecionada, int idFuncionario) {
        preencherCampos(linhaSelecionada, idFuncionario);
        bloquearCampos();
    }

    //COSTRUTOR PARA EDITAR UM FUNCIONARIO SELECIONADO
    public InserirFuncionario(DefaultTableModel modelo, int linhaSelecionada, int idFuncionario) {
        this.modelo = modelo;
        preencherCampos(linhaSelecionada, idFuncionario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        bgSexo = new javax.swing.ButtonGroup();
        PainelFundo = new javax.swing.JPanel();
        cadastroFuncionarios = new javax.swing.JTabbedPane();
        dadosPessoais = new javax.swing.JPanel();
        nome = new javax.swing.JLabel();
        txNome = new javax.swing.JTextField();
        cpf = new javax.swing.JLabel();
        rg = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFeminino = new javax.swing.JRadioButton();
        dataNascimento = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        txId = new javax.swing.JTextField();
        obrigatorio = new javax.swing.JLabel();
        txRg = new javax.swing.JFormattedTextField();
        txCpf = new javax.swing.JFormattedTextField();
        txDtNascimento = new javax.swing.JFormattedTextField();
        txTelefone = new javax.swing.JFormattedTextField();
        dadosProfissionais = new javax.swing.JPanel();
        ctps = new javax.swing.JLabel();
        txCtps = new javax.swing.JTextField();
        dtAdmissao = new javax.swing.JLabel();
        dtDemissao = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        login = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        txLogin = new javax.swing.JTextField();
        observacao = new javax.swing.JLabel();
        txSenha = new javax.swing.JPasswordField();
        txDtAdmissao = new javax.swing.JFormattedTextField();
        txDtDemissao = new javax.swing.JFormattedTextField();
        salario = new javax.swing.JLabel();
        txSalario = new javax.swing.JFormattedTextField();
        scrollTxObservacao = new javax.swing.JScrollPane();
        txObservacao = new javax.swing.JTextArea();
        endereco = new javax.swing.JPanel();
        rua = new javax.swing.JLabel();
        cidade = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        complemento = new javax.swing.JLabel();
        txRua = new javax.swing.JTextField();
        txNumero = new javax.swing.JTextField();
        txComplemento = new javax.swing.JTextField();
        txEstado = new javax.swing.JTextField();
        txCidade = new javax.swing.JTextField();
        idEndereco = new javax.swing.JLabel();
        txIdEndereco = new javax.swing.JTextField();
        cep = new javax.swing.JLabel();
        txCep = new javax.swing.JFormattedTextField();
        bairro = new javax.swing.JLabel();
        txBairro = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PainelFundo.setBackground(new java.awt.Color(217, 176, 60));
        PainelFundo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FUNCIONÁRIO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        PainelFundo.setMaximumSize(new java.awt.Dimension(800, 600));
        PainelFundo.setMinimumSize(new java.awt.Dimension(800, 600));
        PainelFundo.setPreferredSize(new java.awt.Dimension(800, 600));
        PainelFundo.setRequestFocusEnabled(false);

        cadastroFuncionarios.setBackground(new java.awt.Color(255, 255, 153));

        dadosPessoais.setBackground(new java.awt.Color(255, 255, 153));

        nome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nome.setText("NOME *");

        cpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cpf.setText("CPF *");

        rg.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rg.setText("RG *");

        sexo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        sexo.setText("SEXO *");

        bgSexo.add(rbMasculino);
        rbMasculino.setText("Masculino");

        bgSexo.add(rbFeminino);
        rbFeminino.setText("Feminino");

        dataNascimento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dataNascimento.setText("DATA DE NASCIMENTO *");

        telefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        telefone.setText("TELEFONE *");

        id.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        id.setText("ID");

        txId.setEditable(false);

        obrigatorio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        obrigatorio.setText("* CAMPO OBRIGATÓRIO");

        try {
            txRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txRg.setToolTipText("");

        try {
            txCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txDtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout dadosPessoaisLayout = new javax.swing.GroupLayout(dadosPessoais);
        dadosPessoais.setLayout(dadosPessoaisLayout);
        dadosPessoaisLayout.setHorizontalGroup(
            dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosPessoaisLayout.createSequentialGroup()
                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosPessoaisLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dadosPessoaisLayout.createSequentialGroup()
                                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome)
                                    .addComponent(cpf)
                                    .addComponent(sexo))
                                .addGap(109, 109, 109)
                                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(rbMasculino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbFeminino))
                                    .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(dadosPessoaisLayout.createSequentialGroup()
                                            .addComponent(txCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(37, 37, 37)
                                            .addComponent(rg)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txRg, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dadosPessoaisLayout.createSequentialGroup()
                                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataNascimento)
                                    .addComponent(telefone))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(txDtNascimento)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dadosPessoaisLayout.createSequentialGroup()
                                .addComponent(id)
                                .addGap(18, 18, 18)
                                .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(dadosPessoaisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(obrigatorio)))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        dadosPessoaisLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {id, txId});

        dadosPessoaisLayout.setVerticalGroup(
            dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosPessoaisLayout.createSequentialGroup()
                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosPessoaisLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(nome)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosPessoaisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpf)
                    .addComponent(rg)
                    .addComponent(txRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFeminino)
                    .addComponent(sexo)
                    .addComponent(rbMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascimento)
                    .addComponent(txDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefone)
                    .addComponent(txTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(obrigatorio)
                .addGap(38, 38, 38)
                .addGroup(dadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        dadosPessoaisLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {id, txId});

        rbMasculino.getAccessibleContext().setAccessibleName("");
        rbMasculino.getAccessibleContext().setAccessibleDescription("");
        rbFeminino.getAccessibleContext().setAccessibleName("");
        rbFeminino.getAccessibleContext().setAccessibleDescription("");

        cadastroFuncionarios.addTab("DADOS PESSOAIS", dadosPessoais);

        dadosProfissionais.setBackground(new java.awt.Color(255, 255, 153));

        ctps.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ctps.setText("CARTEIRA DE TRABALHO *");

        dtAdmissao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dtAdmissao.setText("DATA DE ADMISSÃO *");

        dtDemissao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dtDemissao.setText("DATA DE DEMISSÃO");

        login.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        login.setText("LOGIN");

        senha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        senha.setText("SENHA");

        observacao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        observacao.setText("OBSERVAÇÕES");

        try {
            txDtAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txDtDemissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        salario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        salario.setText("SALÁRIO *");

        txObservacao.setColumns(20);
        txObservacao.setRows(5);
        scrollTxObservacao.setViewportView(txObservacao);

        javax.swing.GroupLayout dadosProfissionaisLayout = new javax.swing.GroupLayout(dadosProfissionais);
        dadosProfissionais.setLayout(dadosProfissionaisLayout);
        dadosProfissionaisLayout.setHorizontalGroup(
            dadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
            .addGroup(dadosProfissionaisLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosProfissionaisLayout.createSequentialGroup()
                        .addGroup(dadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 39, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(dadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txLogin)
                            .addComponent(txSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dadosProfissionaisLayout.createSequentialGroup()
                        .addGroup(dadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctps)
                            .addComponent(dtAdmissao)
                            .addComponent(dtDemissao)
                            .addComponent(observacao))
                        .addGap(18, 18, 18)
                        .addGroup(dadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dadosProfissionaisLayout.createSequentialGroup()
                                .addGroup(dadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txCtps)
                                    .addComponent(txDtAdmissao)
                                    .addComponent(txDtDemissao))
                                .addGap(18, 18, 18)
                                .addComponent(salario)
                                .addGap(18, 18, 18)
                                .addComponent(txSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrollTxObservacao))))
                .addGap(1, 1, 1))
        );

        dadosProfissionaisLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ctps, dtAdmissao, dtDemissao, txCtps});

        dadosProfissionaisLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {login, senha, txLogin, txSenha});

        dadosProfissionaisLayout.setVerticalGroup(
            dadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosProfissionaisLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctps)
                    .addComponent(txCtps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salario)
                    .addComponent(txSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtAdmissao)
                    .addComponent(txDtAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtDemissao)
                    .addComponent(txDtDemissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(observacao)
                    .addComponent(scrollTxObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(dadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login)
                    .addComponent(txLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dadosProfissionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senha)
                    .addComponent(txSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        dadosProfissionaisLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ctps, dtAdmissao, dtDemissao, txCtps});

        dadosProfissionaisLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {login, senha, txLogin, txSenha});

        cadastroFuncionarios.addTab("DADOS PROFISSIONAIS", dadosProfissionais);

        endereco.setBackground(new java.awt.Color(255, 255, 153));

        rua.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rua.setText("RUA *");

        cidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cidade.setText("CIDADE *");

        estado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        estado.setText("ESTADO *");

        numero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numero.setText("NÚMERO *");

        complemento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        complemento.setText("COMPLEMENTO");

        idEndereco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        idEndereco.setText("ID");

        txIdEndereco.setEditable(false);

        cep.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cep.setText("CEP");

        bairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bairro.setText("BAIRRO");

        txBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBairroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enderecoLayout = new javax.swing.GroupLayout(endereco);
        endereco.setLayout(enderecoLayout);
        enderecoLayout.setHorizontalGroup(
            enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(enderecoLayout.createSequentialGroup()
                            .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(enderecoLayout.createSequentialGroup()
                                        .addComponent(cep)
                                        .addGap(74, 74, 74))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enderecoLayout.createSequentialGroup()
                                        .addComponent(estado)
                                        .addGap(28, 28, 28)))
                                .addGroup(enderecoLayout.createSequentialGroup()
                                    .addComponent(numero)
                                    .addGap(28, 28, 28)))
                            .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txEstado)
                                .addGroup(enderecoLayout.createSequentialGroup()
                                    .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(enderecoLayout.createSequentialGroup()
                                            .addComponent(txNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(complemento))
                                        .addComponent(txCep, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(enderecoLayout.createSequentialGroup()
                            .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rua)
                                .addComponent(bairro))
                            .addGap(26, 26, 26)
                            .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txRua, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(enderecoLayout.createSequentialGroup()
                            .addComponent(cidade)
                            .addGap(26, 26, 26)
                            .addComponent(txCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txComplemento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enderecoLayout.createSequentialGroup()
                        .addComponent(idEndereco)
                        .addGap(29, 29, 29)
                        .addComponent(txIdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        enderecoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cidade, complemento, estado, numero, rua});

        enderecoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {idEndereco, txIdEndereco});

        enderecoLayout.setVerticalGroup(
            enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidade)
                    .addComponent(txCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairro)
                    .addComponent(txBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rua)
                    .addComponent(txRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero)
                    .addComponent(txNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complemento)
                    .addComponent(txComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estado))
                .addGap(20, 20, 20)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cep)
                    .addComponent(txCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idEndereco)
                    .addComponent(txIdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        enderecoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cidade, complemento, estado, numero, rua, txCidade, txComplemento, txEstado, txNumero, txRua});

        enderecoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {idEndereco, txIdEndereco});

        cadastroFuncionarios.addTab("ENDEREÇO", endereco);

        btLimpar.setText("LIMPAR");
        btLimpar.setBorderPainted(false);
        btLimpar.setContentAreaFilled(false);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSalvar.setText("SALVAR");
        btSalvar.setBorderPainted(false);
        btSalvar.setContentAreaFilled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelFundoLayout = new javax.swing.GroupLayout(PainelFundo);
        PainelFundo.setLayout(PainelFundoLayout);
        PainelFundoLayout.setHorizontalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFundoLayout.createSequentialGroup()
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelFundoLayout.createSequentialGroup()
                        .addGap(527, 527, 527)
                        .addComponent(btSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar))
                    .addGroup(PainelFundoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(cadastroFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PainelFundoLayout.setVerticalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFundoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cadastroFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btLimpar))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        
        Funcionario f = new Funcionario();
        
        f.setCpf(txCpf.getText());
        f.setLogin(txLogin.getText());
        f.setRg(txRg.getText());
        f.setSenha(txSenha.getText());
        f.setTelefone(txTelefone.getText());
        f.setcTrabalho(txCtps.getText());
        f.setNome(txNome.getText());
        f.setSalario(Double.parseDouble(txSalario.getText()));
        try {
            String data = txDtAdmissao.getText();
            f.setDtAdmissao(new SimpleDateFormat("dd/mm/yyyy").parse(data));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "FORMATO INVÁLIDO! UTILIZE: DD/MM/YYYY\n" + ex);
        }
        try {
            String data = txDtDemissao.getText();
            f.setDtDemissao(new SimpleDateFormat("dd/mm/yyyy").parse(data));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "FORMATO INVÁLIDO! UTILIZE: DD/MM/YYYY\n" + ex);
        }
        try {
            String data = txDtNascimento.getText();
            f.setDtNascimento(new SimpleDateFormat("dd/mm/yyyy").parse(data));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "FORMATO INVÁLIDO! UTILIZE: DD/MM/YYYY\n" + ex);
        }
        if (rbMasculino.isSelected()) {
            f.setSexo('M');
        } else {
            f.setSexo('F');
        }
        
        Endereco e = new Endereco();
        
        e.setCidade(txCidade.getText());
        e.setComplemento(txComplemento.getText());
        e.setEstado(txEstado.getText());
        e.setNumero(Integer.parseInt(txNumero.getText()));
        e.setRua(txRua.getText());
        e.setCep(txCep.getText());
        e.setBairro(txBairro.getText());
        if (!(txIdEndereco.getText().equals("") | (txIdEndereco.getText().equals(null)))) {
            e.setCodigo(Integer.parseInt(txIdEndereco.getText()));
        }
        f.setEndereco(e);
        
        FuncionarioController fc = new FuncionarioController();
        
        if (!(txId.getText().equals("") | (txId.getText().equals(null)))) {
            f.setCodigo(Integer.parseInt(txId.getText()));
            fc.salvar(f);
            
            modelo.removeRow(linhaSelecionada);
            modelo.addRow(new Object[]{f.getCodigo(), f.getCpf(), f.getDtAdmissao(), f.getDtDemissao(), f.getDtNascimento(), f.getLogin(), f.getNome(), f.getRg(), f.getSenha(), f.getTelefone(), f.getcTrabalho(), f.getSalario()});
            dispose();
        } else {
            fc.salvar(f);
            dispose();
        }

    }//GEN-LAST:event_btSalvarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txObservacao.setText(null);//GEN-HEADEREND:event_btLimparActionPerformed
        txCpf.setText(null);
        txCtps.setText(null);
        txDtAdmissao.setText(null);
        txDtDemissao.setText(null);
        txDtNascimento.setText(null);
        txLogin.setText(null);
        txNome.setText(null);
        txSenha.setText(null);
        txTelefone.setText(null);
        txRg.setText(null);
        txSalario.setText(null);
        
        txCidade.setText(null);
        txComplemento.setText(null);
        txEstado.setText(null);
        txNumero.setText(null);
        txRua.setText(null);
        txCep.setText(null);
        txBairro.setText(null);
    }//GEN-LAST:event_btLimparActionPerformed

    private void txBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txBairroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelFundo;
    private javax.swing.JLabel bairro;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTabbedPane cadastroFuncionarios;
    private javax.swing.JLabel cep;
    private javax.swing.JLabel cidade;
    private javax.swing.JLabel complemento;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel ctps;
    private javax.swing.JPanel dadosPessoais;
    private javax.swing.JPanel dadosProfissionais;
    private javax.swing.JLabel dataNascimento;
    private javax.swing.JLabel dtAdmissao;
    private javax.swing.JLabel dtDemissao;
    private javax.swing.JPanel endereco;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel id;
    private javax.swing.JLabel idEndereco;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel login;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel numero;
    private javax.swing.JLabel obrigatorio;
    private javax.swing.JLabel observacao;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JLabel rg;
    private javax.swing.JLabel rua;
    private javax.swing.JLabel salario;
    private javax.swing.JScrollPane scrollTxObservacao;
    private javax.swing.JLabel senha;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel sexo;
    private javax.swing.JLabel telefone;
    private javax.swing.JTextField txBairro;
    private javax.swing.JFormattedTextField txCep;
    private javax.swing.JTextField txCidade;
    private javax.swing.JTextField txComplemento;
    private javax.swing.JFormattedTextField txCpf;
    private javax.swing.JTextField txCtps;
    private javax.swing.JFormattedTextField txDtAdmissao;
    private javax.swing.JFormattedTextField txDtDemissao;
    private javax.swing.JFormattedTextField txDtNascimento;
    private javax.swing.JTextField txEstado;
    private javax.swing.JTextField txId;
    private javax.swing.JTextField txIdEndereco;
    private javax.swing.JTextField txLogin;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txNumero;
    private javax.swing.JTextArea txObservacao;
    private javax.swing.JFormattedTextField txRg;
    private javax.swing.JTextField txRua;
    private javax.swing.JFormattedTextField txSalario;
    private javax.swing.JPasswordField txSenha;
    private javax.swing.JFormattedTextField txTelefone;
    // End of variables declaration//GEN-END:variables

    private void preencherCampos(int linhaSelecionada, int idFuncionario) {
        initComponents();
        this.linhaSelecionada = linhaSelecionada;
        setLocationRelativeTo(null);
        
        FuncionarioController fc = new FuncionarioController();
        Funcionario f = fc.listarFuncionarioPorId(idFuncionario);

        //FUNCIONARIO
        txId.setText(String.valueOf(f.getCodigo()));
        txSalario.setText(String.valueOf(f.getSalario()));
        txCpf.setText(f.getCpf());
        txCtps.setText(f.getcTrabalho());
        txLogin.setText(f.getLogin());
        txNome.setText(f.getNome());
        txRg.setText(f.getRg());
        txSenha.setText(f.getSenha());
        txTelefone.setText(f.getTelefone());
        if (f.getSexo() == 'F') {
            rbFeminino.setSelected(true);
        } else {
            rbMasculino.setSelected(true);
        }
        SimpleDateFormat formataDtAdmissao = new SimpleDateFormat("dd/MM/yyyy");
        String dtAdmissaoEdt = formataDtAdmissao.format(f.getDtAdmissao());
        txDtAdmissao.setText(dtAdmissaoEdt);
        SimpleDateFormat formataDtDemissao = new SimpleDateFormat("dd/MM/yyyy");
        String dtDemissaoEdt = formataDtDemissao.format(f.getDtDemissao());
        txDtDemissao.setText(dtDemissaoEdt);
        SimpleDateFormat formatadtNascimento = new SimpleDateFormat("dd/MM/yyyy");
        String dtNascimentoEdt = formatadtNascimento.format(f.getDtNascimento());
        txDtNascimento.setText(dtNascimentoEdt);
        //ENDEREÇO
        txIdEndereco.setText(String.valueOf(f.getEndereco().getCodigo()));
        txNumero.setText(String.valueOf(f.getEndereco().getNumero()));
        txCidade.setText(f.getEndereco().getCidade());
        txComplemento.setText(f.getEndereco().getComplemento());
        txEstado.setText(f.getEndereco().getEstado());
        txRua.setText(f.getEndereco().getRua());
        txCep.setText(f.getEndereco().getCep());
        txBairro.setText(f.getEndereco().getCep());
    }
    
    private void bloquearCampos() {
        txNome.setEditable(false);
        txCep.setEditable(false);
        txCidade.setEditable(false);
        txComplemento.setEditable(false);
        txCpf.setEditable(false);
        txCtps.setEditable(false);
        txDtDemissao.setEditable(false);
        txDtNascimento.setEditable(false);
        txEstado.setEditable(false);
        txLogin.setEditable(false);
        txNumero.setEditable(false);
        txObservacao.setEditable(false);
        txRg.setEditable(false);
        txSalario.setEditable(false);
        txRua.setEditable(false);
        txTelefone.setEditable(false);
        txDtAdmissao.setEditable(false);
        rbFeminino.setEnabled(false);
        rbMasculino.setEnabled(false);
        txSenha.setEditable(false);
        btLimpar.setEnabled(false);
        btSalvar.setEnabled(false);
        txBairro.setEnabled(false);
    }
}
