package view.inserir;

import controller.InvestimentoController;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.negocio.Investimento;

public class InserirInvestimento extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    private int linhaSelecionada;

    public InserirInvestimento(DefaultTableModel modelo) {
        initComponents();
        setLocationRelativeTo(null);
        this.modelo = modelo;
    }

    public InserirInvestimento(DefaultTableModel modelo, int linhaSelecionada, int idInvestimento) {
        initComponents();
        this.modelo = modelo;
        this.linhaSelecionada = linhaSelecionada;
        setLocationRelativeTo(null);

        InvestimentoController ic = new InvestimentoController();
        Investimento i = ic.listarInvestimentoPorId(idInvestimento);

        txId.setText(String.valueOf(i.getCodigo()));
        txDescricao.setText(i.getDescricaoInvestimento());
        txFormaPagamento.setText(i.getFormaPagamento());
        txNumeroParcela.setText(String.valueOf(i.getNumeroParcelas()));
        txValorParcela.setText(String.valueOf(i.getValorParcela()));
        txValorTotal.setText(String.valueOf(i.getValorTotal()));

        SimpleDateFormat formataDtInvestimeto = new SimpleDateFormat("dd/MM/yyyy");
        String dtInvestimentoEdt = formataDtInvestimeto.format(i.getDtInvestimento());
        txDtInvestimento.setText(dtInvestimentoEdt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        cadastroInvestimento = new javax.swing.JTabbedPane();
        investimento = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        descricaoInvestimento = new javax.swing.JLabel();
        formaPagamento = new javax.swing.JLabel();
        valorTotal = new javax.swing.JLabel();
        valorParcela = new javax.swing.JLabel();
        numeroParcela = new javax.swing.JLabel();
        dtInvestimento = new javax.swing.JLabel();
        txId = new javax.swing.JTextField();
        txDtInvestimento = new javax.swing.JFormattedTextField();
        txFormaPagamento = new javax.swing.JFormattedTextField();
        txValorTotal = new javax.swing.JFormattedTextField();
        txValorParcela = new javax.swing.JFormattedTextField();
        txNumeroParcela = new javax.swing.JFormattedTextField();
        scrollDescricao = new javax.swing.JScrollPane();
        txDescricao = new javax.swing.JTextArea();
        btSalvar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        id.setText("ID");

        descricaoInvestimento.setText("DESCRIÇÃO");

        formaPagamento.setText("FORMA DE PAGAMENTO");

        valorTotal.setText("VALOR TOTAL");

        valorParcela.setText("VALOR DA PARCELA");

        numeroParcela.setText("NÚMERO DE PARCELAS");

        dtInvestimento.setText("DATA");

        txId.setEditable(false);

        try {
            txDtInvestimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txDescricao.setColumns(20);
        txDescricao.setRows(5);
        scrollDescricao.setViewportView(txDescricao);

        javax.swing.GroupLayout investimentoLayout = new javax.swing.GroupLayout(investimento);
        investimento.setLayout(investimentoLayout);
        investimentoLayout.setHorizontalGroup(
            investimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(investimentoLayout.createSequentialGroup()
                .addGroup(investimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(investimentoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(investimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(investimentoLayout.createSequentialGroup()
                                .addComponent(numeroParcela)
                                .addGap(18, 18, 18)
                                .addComponent(txNumeroParcela))
                            .addGroup(investimentoLayout.createSequentialGroup()
                                .addComponent(valorTotal)
                                .addGap(18, 18, 18)
                                .addComponent(txValorTotal))
                            .addGroup(investimentoLayout.createSequentialGroup()
                                .addComponent(id)
                                .addGap(18, 18, 18)
                                .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(investimentoLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(valorParcela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(txValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, investimentoLayout.createSequentialGroup()
                                .addComponent(formaPagamento)
                                .addGap(18, 18, 18)
                                .addComponent(txFormaPagamento))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, investimentoLayout.createSequentialGroup()
                                .addComponent(dtInvestimento)
                                .addGap(42, 42, 42)
                                .addComponent(txDtInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(investimentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(descricaoInvestimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrollDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        investimentoLayout.setVerticalGroup(
            investimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(investimentoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(investimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(investimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txDtInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtInvestimento))
                .addGap(18, 18, 18)
                .addGroup(investimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formaPagamento)
                    .addComponent(txFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(investimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorTotal)
                    .addComponent(txValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(investimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorParcela)
                    .addComponent(txValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(investimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroParcela)
                    .addComponent(txNumeroParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(investimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(investimentoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(descricaoInvestimento))
                    .addComponent(scrollDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cadastroInvestimento.addTab("INVESTIMENTOS", investimento);

        btSalvar.setText("SALVAR");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btLimpar.setText("LIMPAR");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelFundoLayout = new javax.swing.GroupLayout(painelFundo);
        painelFundo.setLayout(painelFundoLayout);
        painelFundoLayout.setHorizontalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(cadastroInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar)
                .addGap(18, 18, 18)
                .addComponent(btLimpar)
                .addGap(80, 80, 80))
        );
        painelFundoLayout.setVerticalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(cadastroInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btLimpar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed

        txDescricao.setText(null);
        txDtInvestimento.setText(null);
        txFormaPagamento.setText(null);
        txNumeroParcela.setText(null);
        txValorParcela.setText(null);
        txValorTotal.setText(null);

    }//GEN-LAST:event_btLimparActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        Investimento i = new Investimento();

        i.setDescricaoInvestimento(txDescricao.getText());
        i.setFormaPagamento(txFormaPagamento.getText());
        i.setNumeroParcelas(Integer.parseInt(txNumeroParcela.getText()));
        i.setValorParcela(Double.parseDouble(txValorParcela.getText()));
        i.setValorTotal(Double.parseDouble(txValorTotal.getText()));

        try {
            String data = txDtInvestimento.getText();
            i.setDtInvestimento(new SimpleDateFormat("dd/mm/yyyy").parse(data));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "FORMATO INVÁLIDO! UTILIZE: DD/MM/YYYY\n" + ex);
        }

        InvestimentoController ic = new InvestimentoController();

        if (!(txId.getText().equals("") | (txId.getText().equals(null)))) {
            i.setCodigo(Integer.parseInt(txId.getText()));
            ic.salvar(i);

            modelo.removeRow(linhaSelecionada);
            modelo.addRow(new Object[]{i.getCodigo(), i.getDescricaoInvestimento(), i.getDtInvestimento(), i.getFormaPagamento(), i.getNumeroParcelas(), i.getValorParcela(), i.getValorTotal()});
            dispose();
        } else {
            ic.salvar(i);
            dispose();
        }
    }//GEN-LAST:event_btSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTabbedPane cadastroInvestimento;
    private javax.swing.JLabel descricaoInvestimento;
    private javax.swing.JLabel dtInvestimento;
    private javax.swing.JLabel formaPagamento;
    private javax.swing.JLabel id;
    private javax.swing.JPanel investimento;
    private javax.swing.JLabel numeroParcela;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JScrollPane scrollDescricao;
    private javax.swing.JTextArea txDescricao;
    private javax.swing.JFormattedTextField txDtInvestimento;
    private javax.swing.JFormattedTextField txFormaPagamento;
    private javax.swing.JTextField txId;
    private javax.swing.JFormattedTextField txNumeroParcela;
    private javax.swing.JFormattedTextField txValorParcela;
    private javax.swing.JFormattedTextField txValorTotal;
    private javax.swing.JLabel valorParcela;
    private javax.swing.JLabel valorTotal;
    // End of variables declaration//GEN-END:variables
}
