package view.inserir;

import controller.FornecedorController;
import controller.SuprimentoController;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.negocio.Fornecedor;
import modelo.negocio.Suprimento;

public class InserirSuprimento extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    private int linhaSelecionada;

    //INSERIR
    public InserirSuprimento(DefaultTableModel modelo) {
        initComponents();
        setLocationRelativeTo(null);
        this.modelo = modelo;
        carregarCombo();
        setResizable(false);

    }

    //EDITAR LINHA SELECIONADA 
    public InserirSuprimento(DefaultTableModel modelo, int linhaSelecionada, int idSuprimento) {
        this.modelo = modelo;

        preencherCampos(linhaSelecionada, idSuprimento);

    }

    //VISUALIZAR LINHA SELECIONADA
    public InserirSuprimento(int linhaSelecionada, int idSuprimento) {
        preencherCampos(linhaSelecionada, idSuprimento);
        bloquearCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgProducao = new javax.swing.ButtonGroup();
        bgNotaFiscal = new javax.swing.ButtonGroup();
        painelFundo = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        nome = new javax.swing.JLabel();
        txNome = new javax.swing.JTextField();
        formaPagamento = new javax.swing.JLabel();
        cbFormaPagamento = new javax.swing.JComboBox();
        valor = new javax.swing.JLabel();
        txValor = new javax.swing.JTextField();
        notaFiscal = new javax.swing.JLabel();
        rbNao1 = new javax.swing.JRadioButton();
        rbSim1 = new javax.swing.JRadioButton();
        fornecedor = new javax.swing.JLabel();
        cbFornecedor = new javax.swing.JComboBox();
        txId = new javax.swing.JTextField();
        cbOutro = new javax.swing.JCheckBox();
        producao = new javax.swing.JLabel();
        rbSim = new javax.swing.JRadioButton();
        rbNao = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelFundo.setBackground(java.awt.Color.white);

        btSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btSalvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        btSalvar.setActionCommand("");
        btSalvar.setBorder(null);
        btSalvar.setBorderPainted(false);
        btSalvar.setContentAreaFilled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clean2.png"))); // NOI18N
        btLimpar.setBorder(null);
        btLimpar.setBorderPainted(false);
        btLimpar.setContentAreaFilled(false);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        nome.setText("Nome*:  ");

        formaPagamento.setText("Forma de Pagamento:  ");

        cbFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Dinheiro", "Cartão de Crédito/Débito", "Outro" }));

        valor.setText("Valor:  ");

        notaFiscal.setText("Nota Fiscal:    ");

        rbNao1.setBackground(new java.awt.Color(255, 255, 255));
        bgNotaFiscal.add(rbNao1);
        rbNao1.setText("NÃO");

        rbSim1.setBackground(new java.awt.Color(255, 255, 255));
        bgNotaFiscal.add(rbSim1);
        rbSim1.setText("SIM");

        fornecedor.setText("Fornecedor:   ");

        txId.setEditable(false);

        cbOutro.setBackground(java.awt.Color.white);
        cbOutro.setText("Outro");

        producao.setText("É da Produção?*:  ");

        rbSim.setBackground(new java.awt.Color(255, 255, 255));
        bgProducao.add(rbSim);
        rbSim.setText("SIM");

        rbNao.setBackground(new java.awt.Color(255, 255, 255));
        bgProducao.add(rbNao);
        rbNao.setText("NÃO");

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelFundoLayout = new javax.swing.GroupLayout(painelFundo);
        painelFundo.setLayout(painelFundoLayout);
        painelFundoLayout.setHorizontalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelFundoLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(painelFundoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome)
                            .addComponent(fornecedor)
                            .addComponent(valor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txValor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelFundoLayout.createSequentialGroup()
                                .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbOutro)))
                        .addGap(24, 24, 24)))
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFundoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(painelFundoLayout.createSequentialGroup()
                        .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(producao)
                            .addComponent(notaFiscal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelFundoLayout.createSequentialGroup()
                                .addComponent(rbSim1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbNao1))
                            .addGroup(painelFundoLayout.createSequentialGroup()
                                .addComponent(rbSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbNao)))
                        .addContainerGap(275, Short.MAX_VALUE))))
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formaPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelFundoLayout.setVerticalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFundoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(producao)
                    .addComponent(rbSim)
                    .addComponent(rbNao))
                .addGap(20, 20, 20)
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fornecedor)
                    .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOutro)
                    .addComponent(notaFiscal)
                    .addComponent(rbSim1)
                    .addComponent(rbNao1))
                .addGap(20, 20, 20)
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor))
                .addGap(20, 20, 20)
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formaPagamento)
                    .addComponent(cbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Suprimento s = new Suprimento();

        s.setFormaPagamento(cbFormaPagamento.getSelectedItem() + "");

        //Quero ver fazer listar e editar
        if (cbOutro.isSelected()) {
            s.setFornecedor(null);
        } else {
            s.setFornecedor((Fornecedor) cbFornecedor.getSelectedItem());
        }

        s.setValor(Double.parseDouble(txValor.getText()));
        

      //  try {
        //    String data = txDtValidade.getText();
        //    s.setDtVencimento(new SimpleDateFormat("dd/mm/yyyy").parse(data));
        //} catch (Exception ex) {
          //  JOptionPane.showMessageDialog(null, "FORMATO INVÁLIDO! UTILIZE: DD/MM/YYYY\n" + ex);
       // }

        if (rbNao1.isSelected()) {
            s.setNotaFiscal('N');
        } else {
            s.setNotaFiscal('S');
        }

     //   s.setDescricao(txDescricao.getText());
        s.setNome(txNome.getText());
       // s.setQtdade(Integer.parseInt(txQntdade.getText()));

        if (rbNao.isSelected()) {
            s.setProducao('N');
        } else {
            s.setProducao('S');
        }

        SuprimentoController sc = new SuprimentoController();

        if (!(txId.getText().equals("") | (txId.getText().equals(null)))) {
            s.setCodigo(Integer.parseInt(txId.getText()));
            sc.salvar(s);

            modelo.removeRow(linhaSelecionada);
            modelo.addRow(new Object[]{s.getCodigo(), s.getDescricao(), s.getNome(), s.getQtdade()});
            dispose();
        } else {
            sc.salvar(s);
            dispose();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed

     //   txDescricao.setText(null);
        txNome.setText(null);
       // txQntdade.setText(null);

    }//GEN-LAST:event_btLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgNotaFiscal;
    private javax.swing.ButtonGroup bgProducao;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbFormaPagamento;
    private javax.swing.JComboBox cbFornecedor;
    private javax.swing.JCheckBox cbOutro;
    private javax.swing.JLabel formaPagamento;
    private javax.swing.JLabel fornecedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel notaFiscal;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JLabel producao;
    private javax.swing.JRadioButton rbNao;
    private javax.swing.JRadioButton rbNao1;
    private javax.swing.JRadioButton rbSim;
    private javax.swing.JRadioButton rbSim1;
    private javax.swing.JTextField txId;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txValor;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables

    private void preencherCampos(int linhaSelecionada1, int idSuprimento) {
        initComponents();
        this.linhaSelecionada = linhaSelecionada1;
        setLocationRelativeTo(null);
        SuprimentoController sc = new SuprimentoController();
        Suprimento s = sc.listarSuprimentoPorId(idSuprimento);

        txId.setText(String.valueOf(s.getCodigo()));
      //  txDescricao.setText(s.getDescricao());
        txNome.setText(s.getNome());
       // txQntdade.setText(String.valueOf(s.getQtdade()));
        txValor.setText(String.valueOf(s.getValor()));
    

        SimpleDateFormat formataDtValidade = new SimpleDateFormat("dd/MM/yyyy");
        String dtValidadeEdt = formataDtValidade.format(s.getDtVencimento());
     //   txDtValidade.setText(dtValidadeEdt);
        carregarComboESetarValor(s.getFornecedor());

        if (s.getNotaFiscal() == 'N') {
            rbNao1.setSelected(true);
        } else {
            rbSim1.setSelected(true);
        }

        if (s.getProducao() == 'N') {
            rbNao.setSelected(true);
        } else {
            rbSim.setSelected(true);
        }

        if (s.getFormaPagamento().equals("Dinheiro")) {
            cbFormaPagamento.setSelectedIndex(1);
        } else if (s.getFormaPagamento().equals("Cartão de Crédito/Débito")) {
            cbFormaPagamento.setSelectedIndex(2);
        } else if (s.getFormaPagamento().equals("Outro")) {
            cbFormaPagamento.setSelectedIndex(3);
        }
    }

    private void bloquearCampos() {

     //   txDescricao.setEditable(false);
        txNome.setEditable(false);
     //   txQntdade.setEditable(false);
        rbNao.setEnabled(false);
        rbSim.setEnabled(false);
        btLimpar.setEnabled(false);
        btSalvar.setEnabled(false);
        txValor.setEditable(false);
     //   txDtValidade.setEditable(false);
        rbSim1.setEnabled(false);
        rbNao1.setEnabled(false);
        cbOutro.setEnabled(false);
        cbFornecedor.setEnabled(false);

    }

    private void carregarCombo() {
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbFornecedor.getModel();
        comboModel.removeAllElements();
        List<Fornecedor> f = new ArrayList<>();
        FornecedorController fc = new FornecedorController();
        f = fc.listarFornecedor();

        for (int linha = 0; linha < f.size(); linha++) {
            Fornecedor fb = f.get(linha);
            comboModel.addElement(fb);
        }

    }

    private void carregarComboESetarValor(Fornecedor forn) {
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbFornecedor.getModel();
        comboModel.removeAllElements();
        List<Fornecedor> f = new ArrayList<>();
        FornecedorController fc = new FornecedorController();
        f = fc.listarFornecedor();

        for (int linha = 0; linha < f.size(); linha++) {

            Fornecedor fb = f.get(linha);
            comboModel.addElement(fb);

            if (forn != null) {
                if (fb.getCodigo() == forn.getCodigo()) {

                    comboModel.setSelectedItem(fb);
                }
            }

        }

    }
}
