/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.listas.*;

/**
 *
 * @author gustavo_lourenco
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form principal2
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        btFuncinario = new javax.swing.JButton();
        btCliente = new javax.swing.JButton();
        btFornecedor = new javax.swing.JButton();
        btSuprimentos = new javax.swing.JButton();
        btInvestimento = new javax.swing.JButton();
        btProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btFuncinario.setText("FUNCIONARIOS");
        btFuncinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncinarioActionPerformed(evt);
            }
        });

        btCliente.setText("CLIENTE");
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });

        btFornecedor.setText("FORNECEDOR");
        btFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedorActionPerformed(evt);
            }
        });

        btSuprimentos.setText("SUPRIMENTOS");
        btSuprimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuprimentosActionPerformed(evt);
            }
        });

        btInvestimento.setText("INVESTIMENTO");
        btInvestimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInvestimentoActionPerformed(evt);
            }
        });

        btProduto.setText("PRODUTO");
        btProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelFundoLayout = new javax.swing.GroupLayout(painelFundo);
        painelFundo.setLayout(painelFundoLayout);
        painelFundoLayout.setHorizontalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFundoLayout.createSequentialGroup()
                        .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btFuncinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSuprimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btProduto))
                    .addComponent(btInvestimento))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        painelFundoLayout.setVerticalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFuncinario)
                    .addComponent(btProduto))
                .addGap(18, 18, 18)
                .addComponent(btCliente)
                .addGap(18, 18, 18)
                .addComponent(btFornecedor)
                .addGap(18, 18, 18)
                .addComponent(btSuprimentos)
                .addGap(18, 18, 18)
                .addComponent(btInvestimento)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFuncinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncinarioActionPerformed
        ListarFuncionario funcionario = new ListarFuncionario();
        funcionario.setVisible(true);
    }//GEN-LAST:event_btFuncinarioActionPerformed

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        ListarCliente cliente = new ListarCliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_btClienteActionPerformed

    private void btFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedorActionPerformed
        ListarFornecedor fornecedor = new ListarFornecedor();
        fornecedor.setVisible(true);
    }//GEN-LAST:event_btFornecedorActionPerformed

    private void btSuprimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuprimentosActionPerformed
        ListarSuprimento suprimento = new ListarSuprimento();
        suprimento.setVisible(true);
    }//GEN-LAST:event_btSuprimentosActionPerformed

    private void btInvestimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInvestimentoActionPerformed
        ListarInvestimento investimento = new ListarInvestimento();
        investimento.setVisible(true);
    }//GEN-LAST:event_btInvestimentoActionPerformed

    private void btProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutoActionPerformed

        ListarProduto produto = new ListarProduto();
        produto.setVisible(true);

    }//GEN-LAST:event_btProdutoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btFornecedor;
    private javax.swing.JButton btFuncinario;
    private javax.swing.JButton btInvestimento;
    private javax.swing.JButton btProduto;
    private javax.swing.JButton btSuprimentos;
    private javax.swing.JPanel painelFundo;
    // End of variables declaration//GEN-END:variables
}
